### ISSUE TITLE
[v1-0.0.5] Wrong tag name

### ISSUE THREAD

**Issue by HugoGEORGET** [google-cloudsearch/connector-sdk#31]
Hi,

The v1-0.0.5 release name does not follow the naming convention.
Right now, it is "v1.0.0-5" but it should be "v1-0.0.5".

It also makes the README.md invalid since the
```
git checkout tags/v1-0.0.5
```
command will not work.

Is it possible to fix this ?

Thank you.

**Comment by wiarlawd** [comment]
Fixed (I'm not going to delete the bad tag, but at least the instructions will work). Thanks!
